"""initial_schema

Revision ID: 0c937819b2cf
Revises: 
Create Date: 2026-09-14 13:04:59.554952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c937819b2cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_student_id'), 'assessments', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessments_submitted_at'), 'assessments', ['submitted_at'], unique=False)
    op.create_table('background_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_responses_assessment_id'), 'background_responses', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_background_responses_field_name'), 'background_responses', ['field_name'], unique=False)
    op.create_table('domain_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=False),
    sa.Column('t_score', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('screening_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'domain', name='uq_assessment_domain')
    )
    op.create_index(op.f('ix_domain_scores_assessment_id'), 'domain_scores', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_domain_scores_domain'), 'domain_scores', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_scores_screening_level'), 'domain_scores', ['screening_level'], unique=False)
    op.create_table('item_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('response_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'item_number', name='uq_assessment_item')
    )
    op.create_index(op.f('ix_item_responses_assessment_id'), 'item_responses', ['assessment_id'], unique=False)
    op.create_table('safety_flags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_flags_assessment_id'), 'safety_flags', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_safety_flags_created_at'), 'safety_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_safety_flags_status'), 'safety_flags', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_flags_status'), table_name='safety_flags')
    op.drop_index(op.f('ix_safety_flags_created_at'), table_name='safety_flags')
    op.drop_index(op.f('ix_safety_flags_assessment_id'), table_name='safety_flags')
    op.drop_table('safety_flags')
    op.drop_index(op.f('ix_item_responses_assessment_id'), table_name='item_responses')
    op.drop_table('item_responses')
    op.drop_index(op.f('ix_domain_scores_screening_level'), table_name='domain_scores')
    op.drop_index(op.f('ix_domain_scores_domain'), table_name='domain_scores')
    op.drop_index(op.f('ix_domain_scores_assessment_id'), table_name='domain_scores')
    op.drop_table('domain_scores')
    op.drop_index(op.f('ix_background_responses_field_name'), table_name='background_responses')
    op.drop_index(op.f('ix_background_responses_assessment_id'), table_name='background_responses')
    op.drop_table('background_responses')
    op.drop_index(op.f('ix_assessments_submitted_at'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_student_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
